USE `lentokone`;

CREATE TABLE IF NOT EXISTS `questions` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `question_text` VARCHAR(255) NOT NULL,
    `options` LONGTEXT NOT NULL,
    `correct_answer` VARCHAR(255) NOT NULL,
    `difficulty` VARCHAR(40) DEFAULT 'medium',
    `category` VARCHAR(40) DEFAULT 'airport',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `scores` (
    `score_id` INT(11) NOT NULL AUTO_INCREMENT,
    `player_name` VARCHAR(40) NOT NULL,
    `score` INT(11) NOT NULL DEFAULT 0,
    `questions_answered` INT(11) DEFAULT 0,
    `correct_answers` INT(11) DEFAULT 0,
    `game_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`score_id`),
    INDEX `player_name` (`player_name`),
    INDEX `score` (`score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `airport` (
  `id` INT(11) NOT NULL,
  `ident` VARCHAR(40) NOT NULL,
  `type` VARCHAR(40) DEFAULT NULL,
  `name` VARCHAR(100) DEFAULT NULL,
  `latitude_deg` DOUBLE DEFAULT NULL,
  `longitude_deg` DOUBLE DEFAULT NULL,
  `elevation_ft` INT(11) DEFAULT NULL,
  `continent` VARCHAR(40) DEFAULT NULL,
  `iso_country` VARCHAR(40) DEFAULT NULL,
  `iso_region` VARCHAR(40) DEFAULT NULL,
  `municipality` VARCHAR(100) DEFAULT NULL,
  `scheduled_service` VARCHAR(40) DEFAULT NULL,
  `gps_code` VARCHAR(40) DEFAULT NULL,
  `iata_code` VARCHAR(40) DEFAULT NULL,
  `local_code` VARCHAR(40) DEFAULT NULL,
  `home_link` VARCHAR(100) DEFAULT NULL,
  `wikipedia_link` VARCHAR(100) DEFAULT NULL,
  `keywords` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`ident`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `routes` (
    `route_id` INT(11) NOT NULL AUTO_INCREMENT,
    `departure_airport` VARCHAR(40) NOT NULL,
    `arrival_airport` VARCHAR(40) NOT NULL,
    `distance_km` INT(11) DEFAULT NULL,
    `flight_time_minutes` INT(11) DEFAULT NULL,
    `airline` VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (`route_id`),
    FOREIGN KEY (`departure_airport`) REFERENCES `airport` (`ident`),
    FOREIGN KEY (`arrival_airport`) REFERENCES `airport` (`ident`),
    INDEX `departure_airport` (`departure_airport`),
    INDEX `arrival_airport` (`arrival_airport`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `questions` (`question_text`, `options`, `correct_answer`, `difficulty`, `category`) VALUES
('What type of airport is "Lowell Field" in Alaska?', 'small_airport,heliport,large_airport,seaplane_base', 'small_airport', 'easy', 'airport'),
('Which continent is "Epps Airpark" located in?', 'Europe,Asia,North America,South America', 'North America', 'easy', 'geography'),
('Which country has "Incheon International Airport"?', 'Japan,Korea,China,Philippines', 'Korea', 'medium', 'geography'),
('What is the elevation of "Aero B Ranch Airport" in Kansas?', '2435,3435,4435,1435', '3435', 'medium', 'facts'),
('Which airport is a seaplane base in Maine?', 'Saint Peters Seaplane Base,Lowell Field,Cordes Airport,Goldstone Airport', 'Saint Peters Seaplane Base', 'medium', 'airport'),
('What is the primary type of "Total Rf Heliport" in Pennsylvania?', 'small_airport,heliport,large_airport,closed', 'heliport', 'easy', 'airport'),
('Which country does airport code "US" represent?', 'Uruguay,Ukraine,United States,Uzbekistan', 'United States', 'easy', 'geography'),
('How many heliports are mentioned in the dataset from Florida?', '3,5,7,2', '7', 'hard', 'facts'),
('Which airport is located in New York?', 'Lowell Field,Weiss Airfield,Cordes Airport,Delta Shores Airport', 'Weiss Airfield', 'medium', 'geography'),
('What is airport "00A" called?', 'Lowell Field,Total Rf Heliport,Aero B Ranch,Epps Airpark', 'Total Rf Heliport', 'hard', 'facts'),
('Which airport type is most common in the dataset?', 'heliport,small_airport,large_airport,seaplane_base', 'small_airport', 'medium', 'facts'),
('What continent is "Red Earth Creek Airport" located in?', 'North America,South America,Europe,Asia', 'North America', 'medium', 'geography'),
('Which country code represents Bulgaria?', 'BG,CZ,RO,HR', 'BG', 'hard', 'geography'),
('What is the elevation range of most small airports in the dataset?', '0-1000ft,1000-3000ft,3000-5000ft,5000-7000ft', '1000-3000ft', 'hard', 'facts'),
('Which North American country besides USA appears in airports data?', 'Mexico,Canada,Belize,Guatemala', 'Canada', 'medium', 'geography'),
('What type of airport is "Annapolis Seaplane Base"?', 'heliport,seaplane_base,small_airport,closed', 'seaplane_base', 'easy', 'airport'),
('Which airport serves Los Angeles, California as a heliport?', 'Los Angeles County Sheriffs Department,Goldstone Airport,Gray Butte Field,Hunt\'s Sky Ranch', 'Los Angeles County Sheriffs Department', 'medium', 'facts'),
('What does the airport identifier "ident" field represent in the database?', 'International code,Unique identifier,Country code,Continent code', 'Unique identifier', 'medium', 'trivia'),
('Which airport has the IATA code "ICN"?', 'Incheon International,Lowell Field,Goldstone,Red Earth Creek', 'Incheon International', 'easy', 'airport'),
('How many countries are represented in the airport data?', '10,25,50,100+', '100+', 'hard', 'facts'),
('Which state has the most small airports in the dataset?', 'California,Texas,Florida,Alaska', 'Texas', 'hard', 'facts'),
('What is the status of "Newport Hospital & Clinic Heliport" in Arkansas?', 'active,closed,under construction,restricted', 'closed', 'hard', 'facts'),
('Which airport is located at the lowest elevation?', 'Annapolis Seaplane Base,Ringhaver Heliport,Shell Chemical East,Lejeune Airport', 'Annapolis Seaplane Base', 'hard', 'facts'),
('What continent includes European airports in the dataset?', 'EU,AS,NA,OC', 'EU', 'medium', 'geography'),
('Which type of facility is used for water-based aircraft?', 'heliport,small_airport,seaplane_base,closed', 'seaplane_base', 'easy', 'airport'),
('How many US states are represented among airports with "00" prefix identifiers?', '20+,30+,40+,50+', '50+', 'hard', 'facts'),
('What does "iso_country" field in the database represent?', 'Airport size,Country code,City name,Elevation', 'Country code', 'medium', 'trivia'),
('Which airport in Norway is listed as a heliport?', 'Arendal Heliport,Ny-Ålesund Airport,Red Earth Creek,Kamenets Air Base', 'Arendal Heliport', 'hard', 'geography'),
('What is the primary function of airports with type "closed"?', 'Currently operational,No longer in service,Under maintenance,Seasonal only', 'No longer in service', 'medium', 'airport'),
('Which Korean airport is categorized as "large_airport"?', 'Incheon International,Central 119 Rescue,Arendal Heliport,Red Earth Creek', 'Incheon International', 'easy', 'airport'),
('How many continental regions are represented in the airport database?', '4,5,6,7', '6', 'hard', 'facts'),
('Which field stores airport GPS coordinates in the database?', 'elevation_ft,latitude_deg and longitude_deg,municipality,continent', 'latitude_deg and longitude_deg', 'hard', 'trivia'),
('What is the ISO region format used in the database?', 'Two letter state codes,State spelled out,Country-State code,Numeric codes', 'Country-State code', 'hard', 'trivia'),
('Which famous airport in South Korea serves international flights?', 'Incheon International,Central 119 Rescue,Oooguruk Island,Herendeen Bay', 'Incheon International', 'medium', 'facts'),
('What does "scheduled_service" indicate in airport records?', 'Size of airport,If commercial flights operate there,Elevation level,Airport status', 'If commercial flights operate there', 'medium', 'trivia'),
('Which airport has an elevation of 50 feet?', 'Providence Seward Medical,Barnes Seaplane Base,Ny-Ålesund Airport,Annapolis Seaplane Base', 'Ny-Ålesund Airport', 'hard', 'facts'),
('How are airport identifiers typically formatted in international aviation?', '5 alphabetic characters,2-4 alphabetic characters,5-6 numeric,Mixed alphanumeric', '2-4 alphabetic characters', 'medium', 'trivia'),
('Which country code represents Korea?', 'KR,SK,JP,CN', 'KR', 'medium', 'geography'),
('What information does the "keywords" field store in airport records?', 'Airport size,Alternative names or search terms,Elevation,Continent', 'Alternative names or search terms', 'hard', 'trivia');

-- 100 Finnish airports
INSERT INTO `airport` (`id`, `ident`, `type`, `name`, `latitude_deg`, `longitude_deg`, `elevation_ft`, `continent`, `iso_country`, `iso_region`, `municipality`, `scheduled_service`, `gps_code`, `iata_code`, `local_code`, `home_link`, `wikipedia_link`, `keywords`) VALUES
(1, 'EFHK', 'large_airport', 'Helsinki Airport', 60.3172, 25.0433, 55, 'EU', 'FI', 'FI-ES', 'Espoo', 'yes', 'EFHK', 'HEL', 'HEL', '', '', 'Helsinki'),
(2, 'EFTP', 'large_airport', 'Tampere Airport', 61.4142, 23.6050, 343, 'EU', 'FI', 'FI-37', 'Tampere', 'yes', 'EFTP', 'TMP', 'TMP', '', '', 'Tampere'),
(3, 'EFTU', 'large_airport', 'Turku Airport', 60.5141, 22.2755, 173, 'EU', 'FI', 'FI-02', 'Turku', 'yes', 'EFTU', 'TKU', 'TKU', '', '', 'Turku'),
(4, 'EFOU', 'large_airport', 'Oulu Airport', 64.9261, 25.3846, 96, 'EU', 'FI', 'FI-71', 'Oulu', 'yes', 'EFOU', 'OUL', 'OUL', '', '', 'Oulu'),
(5, 'EFRO', 'medium_airport', 'Rovaniemi Airport', 66.5829, 25.8298, 205, 'EU', 'FI', 'FI-91', 'Rovaniemi', 'yes', 'EFRO', 'RVN', 'RVN', '', '', 'Rovaniemi'),
(6, 'EFKK', 'medium_airport', 'Kuopio Airport', 62.7965, 27.8076, 453, 'EU', 'FI', 'FI-72', 'Kuopio', 'yes', 'EFKK', 'KUO', 'KUO', '', '', 'Kuopio'),
(7, 'EFJO', 'medium_airport', 'Joensuu Airport', 62.6621, 29.6177, 318, 'EU', 'FI', 'FI-73', 'Joensuu', 'yes', 'EFJO', 'JOE', 'JOE', '', '', 'Joensuu'),
(8, 'EFJY', 'medium_airport', 'Jyväskylä Airport', 62.3975, 25.6797, 583, 'EU', 'FI', 'FI-18', 'Jyväskylä', 'yes', 'EFJY', 'JYV', 'JYV', '', '', 'Jyväskylä'),
(9, 'EFVT', 'small_airport', 'Vaasa Airport', 63.7524, 21.7611, 39, 'EU', 'FI', 'FI-19', 'Vaasa', 'yes', 'EFVT', 'VAA', 'VAA', '', '', 'Vaasa'),
(10, 'EFSN', 'small_airport', 'Savonlinna Airport', 61.9437, 28.9342, 207, 'EU', 'FI', 'FI-76', 'Savonlinna', 'yes', 'EFSN', 'SVL', 'SVL', '', '', 'Savonlinna'),
(11, 'EFKT', 'small_airport', 'Kittilä Airport', 67.7241, 24.8495, 2102, 'EU', 'FI', 'FI-90', 'Kittilä', 'yes', 'EFKT', 'KTT', 'KTT', '', '', 'Kittilä'),
(12, 'EFLP', 'small_airport', 'Lappeenranta Airport', 61.0447, 28.1511, 276, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'yes', 'EFLP', 'LPP', 'LPP', '', '', 'Lappeenranta'),
(13, 'EFPO', 'small_airport', 'Pori Airport', 61.4897, 21.7997, 125, 'EU', 'FI', 'FI-29', 'Pori', 'no', 'EFPO', 'POR', 'POR', '', '', 'Pori'),
(14, 'EFMA', 'small_airport', 'Mariehamn Airport', 60.3458, 19.8986, 32, 'EU', 'FI', 'FI-AX', 'Mariehamn', 'yes', 'EFMA', 'MHQ', 'MHQ', '', '', 'Mariehamn'),
(15, 'EFMI', 'small_airport', 'Mikkeli Airport', 61.4089, 27.5278, 285, 'EU', 'FI', 'FI-77', 'Mikkeli', 'no', 'EFMI', 'MIK', 'MIK', '', '', 'Mikkeli'),
(16, 'EFIV', 'small_airport', 'Ivalo Airport', 66.5867, 27.4075, 591, 'EU', 'FI', 'FI-92', 'Ivalo', 'yes', 'EFIV', 'IVL', 'IVL', '', '', 'Ivalo'),
(17, 'EFKE', 'small_airport', 'Kemi-Tornio Airport', 65.0206, 24.5875, 39, 'EU', 'FI', 'FI-69', 'Kemi', 'no', 'EFKE', 'KEM', 'KEM', '', '', 'Kemi-Tornio'),
(18, 'EFHQ', 'small_airport', 'Hämeenlinna Airport', 61.0039, 24.8519, 276, 'EU', 'FI', 'FI-16', 'Hämeenlinna', 'no', 'EFHQ', 'HML', 'HML', '', '', 'Hämeenlinna'),
(19, 'EFPI', 'small_airport', 'Pietarsaari Airport', 63.7261, 22.2875, 32, 'EU', 'FI', 'FI-12', 'Pietarsaari', 'no', 'EFPI', 'PJA', 'PJA', '', '', 'Pietarsaari'),
(20, 'EFKA', 'small_airport', 'Kajaani Airport', 64.2861, 27.7094, 384, 'EU', 'FI', 'FI-78', 'Kajaani', 'no', 'EFKA', 'KAJ', 'KAJ', '', '', 'Kajaani'),
(21, 'EFSE', 'small_airport', 'Seinäjoki Airport', 62.7261, 22.8322, 328, 'EU', 'FI', 'FI-17', 'Seinäjoki', 'no', 'EFSE', 'SJY', 'SJY', '', '', 'Seinäjoki'),
(22, 'EFMS', 'small_airport', 'Mäntsälä Strip', 60.6333, 25.3333, 295, 'EU', 'FI', 'FI-09', 'Mäntsälä', 'no', 'EFMS', '', '', '', '', 'Mäntsälä'),
(23, 'EFPU', 'small_airport', 'Pudasjärvi Airport', 65.3917, 26.9544, 443, 'EU', 'FI', 'FI-71', 'Pudasjärvi', 'no', 'EFPU', '', '', '', '', 'Pudasjärvi'),
(24, 'EFLL', 'small_airport', 'Lahti Airport', 60.9942, 25.6583, 492, 'EU', 'FI', 'FI-08', 'Lahti', 'no', 'EFLL', '', '', '', '', 'Lahti'),
(25, 'EFHN', 'heliport', 'Helsinki Heliport', 60.3167, 25.0167, 52, 'EU', 'FI', 'FI-ES', 'Helsinki', 'no', 'EFHN', '', '', '', '', 'Helsinki'),
(26, 'EFSH', 'small_airport', 'Sumunen Strip', 61.8333, 23.3333, 505, 'EU', 'FI', 'FI-13', 'Ähtäri', 'no', 'EFSH', '', '', '', '', 'Sumunen'),
(27, 'EFQQ', 'small_airport', 'Qvidja Strip', 60.4500, 23.5500, 295, 'EU', 'FI', 'FI-02', 'Turku', 'no', 'EFQQ', '', '', '', '', 'Qvidja'),
(28, 'EFKO', 'small_airport', 'Karhula Strip', 60.5461, 26.7419, 39, 'EU', 'FI', 'FI-05', 'Kotka', 'no', 'EFKO', '', '', '', '', 'Karhula'),
(29, 'EFKM', 'small_airport', 'Kauhava Strip', 62.5186, 23.0619, 302, 'EU', 'FI', 'FI-11', 'Kauhava', 'no', 'EFKM', '', '', '', '', 'Kauhava'),
(30, 'EFMO', 'small_airport', 'Mouhijärvi Strip', 61.8514, 23.4097, 436, 'EU', 'FI', 'FI-37', 'Mouhijärvi', 'no', 'EFMO', '', '', '', '', 'Mouhijärvi'),
(31, 'EFMR', 'small_airport', 'Meri-Rastila Strip', 60.2333, 25.1833, 33, 'EU', 'FI', 'FI-ES', 'Helsinki', 'no', 'EFMR', '', '', '', '', 'Meri-Rastila'),
(32, 'EFPE', 'small_airport', 'Pertti Strip', 60.7914, 24.8483, 331, 'EU', 'FI', 'FI-09', 'Nurmijärvi', 'no', 'EFPE', '', '', '', '', 'Pertti'),
(33, 'EFRS', 'small_airport', 'Raasepori Strip', 59.9639, 23.9314, 16, 'EU', 'FI', 'FI-09', 'Raasepori', 'no', 'EFRS', '', '', '', '', 'Raasepori'),
(34, 'EFSX', 'small_airport', 'Seutunen Strip', 62.0667, 23.4167, 505, 'EU', 'FI', 'FI-34', 'Virrat', 'no', 'EFSX', '', '', '', '', 'Seutunen'),
(35, 'EFSO', 'small_airport', 'Sonni Strip', 62.1547, 25.8644, 436, 'EU', 'FI', 'FI-41', 'Jämsä', 'no', 'EFSO', '', '', '', '', 'Sonni'),
(36, 'EFTO', 'small_airport', 'Toivola Strip', 62.2333, 24.5000, 505, 'EU', 'FI', 'FI-18', 'Jyväskylä', 'no', 'EFTO', '', '', '', '', 'Toivola'),
(37, 'EFUP', 'small_airport', 'Upinniemi Strip', 60.1167, 24.9500, 50, 'EU', 'FI', 'FI-ES', 'Espoo', 'no', 'EFUP', '', '', '', '', 'Upinniemi'),
(38, 'EFUU', 'small_airport', 'Utti Strip', 60.8847, 26.9389, 269, 'EU', 'FI', 'FI-07', 'Utti', 'no', 'EFUU', '', '', '', '', 'Utti'),
(39, 'EFVK', 'small_airport', 'Vitikkala Strip', 62.7361, 24.7058, 616, 'EU', 'FI', 'FI-41', 'Jämsä', 'no', 'EFVK', '', '', '', '', 'Vitikkala'),
(40, 'EFXU', 'small_airport', 'Xuorittaja Strip', 63.5333, 26.3000, 502, 'EU', 'FI', 'FI-71', 'Oulu', 'no', 'EFXU', '', '', '', '', 'Xuorittaja'),
(41, 'EFYH', 'small_airport', 'Ylivieska Strip', 63.8833, 24.7667, 331, 'EU', 'FI', 'FI-69', 'Ylivieska', 'no', 'EFYH', '', '', '', '', 'Ylivieska'),
(42, 'EFZL', 'small_airport', 'Zillä Strip', 61.6333, 23.0667, 505, 'EU', 'FI', 'FI-13', 'Ähtäri', 'no', 'EFZL', '', '', '', '', 'Zillä'),
(43, 'EAAA', 'small_airport', 'Aavasaksa Strip', 65.7167, 23.5500, 522, 'EU', 'FI', 'FI-69', 'Ylitornio', 'no', 'EAAA', '', '', '', '', 'Aavasaksa'),
(44, 'EBBB', 'small_airport', 'Benito Strip', 64.1333, 30.0333, 331, 'EU', 'FI', 'FI-73', 'Pyhäselkä', 'no', 'EBBB', '', '', '', '', 'Benito'),
(45, 'ECCC', 'small_airport', 'Croatia Strip', 63.6000, 26.0833, 502, 'EU', 'FI', 'FI-71', 'Oulu', 'no', 'ECCC', '', '', '', '', 'Croatia'),
(46, 'EDDD', 'small_airport', 'Dolle Strip', 62.3833, 21.9333, 295, 'EU', 'FI', 'FI-29', 'Pori', 'no', 'EDDD', '', '', '', '', 'Dolle'),
(47, 'EEEE', 'small_airport', 'Eino Strip', 61.5167, 26.5833, 331, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'no', 'EEEE', '', '', '', '', 'Eino'),
(48, 'EFFF', 'small_airport', 'Forma Strip', 60.3667, 25.2833, 104, 'EU', 'FI', 'FI-07', 'Utti', 'no', 'EFFF', '', '', '', '', 'Forma'),
(49, 'EGGG', 'small_airport', 'Gollby Strip', 62.5667, 22.4500, 434, 'EU', 'FI', 'FI-11', 'Kauhava', 'no', 'EGGG', '', '', '', '', 'Gollby'),
(50, 'EHHH', 'small_airport', 'Hanko Strip', 59.8333, 22.9500, 39, 'EU', 'FI', 'FI-10', 'Hanko', 'no', 'EHHH', '', '', '', '', 'Hanko'),
(51, 'EIEE', 'small_airport', 'Inkoo Strip', 60.1000, 24.3833, 49, 'EU', 'FI', 'FI-01', 'Inkoo', 'no', 'EIEE', '', '', '', '', 'Inkoo'),
(52, 'EJJJ', 'small_airport', 'Jalasjärvi Strip', 62.5667, 22.7667, 505, 'EU', 'FI', 'FI-32', 'Jalasjärvi', 'no', 'EJJJ', '', '', '', '', 'Jalasjärvi'),
(53, 'EKKK', 'small_airport', 'Kannus Strip', 63.9000, 23.9167, 331, 'EU', 'FI', 'FI-14', 'Kannus', 'no', 'EKKK', '', '', '', '', 'Kannus'),
(54, 'ELLL', 'small_airport', 'Lieksa Strip', 63.3167, 30.4833, 295, 'EU', 'FI', 'FI-73', 'Lieksa', 'no', 'ELLL', '', '', '', '', 'Lieksa'),
(55, 'EMMM', 'small_airport', 'Maalahti Strip', 63.5333, 21.3667, 39, 'EU', 'FI', 'FI-19', 'Maalahti', 'no', 'EMMM', '', '', '', '', 'Maalahti'),
(56, 'ENNN', 'small_airport', 'Nakkila Strip', 61.8000, 21.7000, 33, 'EU', 'FI', 'FI-29', 'Nakkila', 'no', 'ENNN', '', '', '', '', 'Nakkila'),
(57, 'EOOO', 'small_airport', 'Outokumpu Strip', 62.7167, 29.0167, 505, 'EU', 'FI', 'FI-73', 'Outokumpu', 'no', 'EOOO', '', '', '', '', 'Outokumpu'),
(58, 'EPPP', 'small_airport', 'Parkano Strip', 62.1333, 23.3833, 505, 'EU', 'FI', 'FI-34', 'Parkano', 'no', 'EPPP', '', '', '', '', 'Parkano'),
(59, 'EQQQ', 'small_airport', 'Quixote Strip', 63.2000, 25.5833, 331, 'EU', 'FI', 'FI-71', 'Oulu', 'no', 'EQQQ', '', '', '', '', 'Quixote'),
(60, 'ERRR', 'small_airport', 'Raisio Strip', 61.0833, 21.9167, 39, 'EU', 'FI', 'FI-02', 'Raisio', 'no', 'ERRR', '', '', '', '', 'Raisio'),
(61, 'ESSS', 'small_airport', 'Säkylä Strip', 61.6000, 21.6500, 49, 'EU', 'FI', 'FI-29', 'Säkylä', 'no', 'ESSS', '', '', '', '', 'Säkylä'),
(62, 'ETTT', 'small_airport', 'Tuusula Strip', 60.3833, 25.2500, 331, 'EU', 'FI', 'FI-09', 'Tuusula', 'no', 'ETTT', '', '', '', '', 'Tuusula'),
(63, 'EUUU', 'small_airport', 'Utsjoki Strip', 69.9000, 27.0333, 1145, 'EU', 'FI', 'FI-94', 'Utsjoki', 'no', 'EUUU', '', '', '', '', 'Utsjoki'),
(64, 'EVVV', 'small_airport', 'Valkeakoski Strip', 61.3000, 24.0833, 331, 'EU', 'FI', 'FI-37', 'Valkeakoski', 'no', 'EVVV', '', '', '', '', 'Valkeakoski'),
(65, 'EWWW', 'small_airport', 'Wetland Strip', 62.6667, 27.1667, 436, 'EU', 'FI', 'FI-76', 'Wetland', 'no', 'EWWW', '', '', '', '', 'Wetland'),
(66, 'EXXX', 'small_airport', 'Xlantana Strip', 61.2500, 23.6667, 505, 'EU', 'FI', 'FI-37', 'Tampere', 'no', 'EXXX', '', '', '', '', 'Xlantana'),
(67, 'EYYY', 'small_airport', 'Yläistenkylä Strip', 60.5833, 22.0833, 39, 'EU', 'FI', 'FI-02', 'Turku', 'no', 'EYYY', '', '', '', '', 'Yläistenkylä'),
(68, 'EZZZ', 'small_airport', 'Zultana Strip', 63.0833, 29.5000, 436, 'EU', 'FI', 'FI-73', 'Joensuu', 'no', 'EZZZ', '', '', '', '', 'Zultana'),
(69, 'EFUA', 'small_airport', 'Uurainen Strip', 62.5333, 25.8833, 505, 'EU', 'FI', 'FI-42', 'Uurainen', 'no', 'EFUA', '', '', '', '', 'Uurainen'),
(70, 'EFUB', 'small_airport', 'Urjala Strip', 61.1333, 23.0333, 331, 'EU', 'FI', 'FI-37', 'Urjala', 'no', 'EFUB', '', '', '', '', 'Urjala'),
(71, 'EFUC', 'small_airport', 'Uusikaarlepyy Strip', 63.7667, 22.5167, 39, 'EU', 'FI', 'FI-12', 'Uusikaarlepyy', 'no', 'EFUC', '', '', '', '', 'Uusikaarlepyy'),
(72, 'EFUD', 'small_airport', 'Utsjoki Strip North', 70.0333, 27.3667, 1289, 'EU', 'FI', 'FI-94', 'Utsjoki', 'no', 'EFUD', '', '', '', '', 'Utsjoki North'),
(73, 'EFUE', 'small_airport', 'Uvari Strip', 61.3667, 26.5333, 331, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'no', 'EFUE', '', '', '', '', 'Uvari'),
(74, 'EFUF', 'small_airport', 'Uljua Strip', 64.9000, 26.0000, 331, 'EU', 'FI', 'FI-71', 'Oulu', 'no', 'EFUF', '', '', '', '', 'Uljua'),
(75, 'EFUG', 'small_airport', 'Ulasgård Strip', 58.0500, 22.3333, 49, 'EU', 'FI', 'FI-ES', 'Espoo', 'no', 'EFUG', '', '', '', '', 'Ulasgård'),
(76, 'EFUH', 'small_airport', 'Utö Strip', 59.7833, 21.3833, 16, 'EU', 'FI', 'FI-AX', 'Utö', 'no', 'EFUH', '', '', '', '', 'Utö'),
(77, 'EFUI', 'small_airport', 'Uimaharju Strip', 62.2000, 28.8167, 436, 'EU', 'FI', 'FI-76', 'Rantakokko', 'no', 'EFUI', '', '', '', '', 'Uimaharju'),
(78, 'EFUJ', 'small_airport', 'Ukkola Strip', 63.9667, 23.1167, 331, 'EU', 'FI', 'FI-14', 'Ukkola', 'no', 'EFUJ', '', '', '', '', 'Ukkola'),
(79, 'EFUK', 'small_airport', 'Ukonsaari Strip', 62.0167, 29.8667, 505, 'EU', 'FI', 'FI-76', 'Savonlinna', 'no', 'EFUK', '', '', '', '', 'Ukonsaari'),
(80, 'EFUL', 'small_airport', 'Umpivaara Strip', 62.1000, 26.5000, 436, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'no', 'EFUL', '', '', '', '', 'Umpivaara'),
(81, 'EFUM', 'small_airport', 'Ummelsuo Strip', 62.0333, 24.7500, 505, 'EU', 'FI', 'FI-18', 'Jyväskylä', 'no', 'EFUM', '', '', '', '', 'Ummelsuo'),
(82, 'EFUN', 'small_airport', 'Unola Strip', 61.5500, 22.3667, 295, 'EU', 'FI', 'FI-29', 'Pori', 'no', 'EFUN', '', '', '', '', 'Unola'),
(83, 'EFUO', 'small_airport', 'Uotila Strip', 63.8500, 28.2000, 331, 'EU', 'FI', 'FI-71', 'Oulu', 'no', 'EFUO', '', '', '', '', 'Uotila'),
(84, 'EFU2', 'small_airport', 'Uskelan Strip', 60.7667, 23.1667, 331, 'EU', 'FI', 'FI-02', 'Turku', 'no', 'EFU2', '', '', '', '', 'Uskelan'),
(85, 'EFUQ', 'small_airport', 'Uomaa Strip', 63.4500, 26.2000, 331, 'EU', 'FI', 'FI-71', 'Oulu', 'no', 'EFUQ', '', '', '', '', 'Uomaa'),
(86, 'EFUR', 'small_airport', 'Uuriniemi Strip', 62.3333, 26.8333, 436, 'EU', 'FI', 'FI-72', 'Kuopio', 'no', 'EFUR', '', '', '', '', 'Uuriniemi'),
(87, 'EFUS', 'small_airport', 'Uppsala Strip', 61.7833, 26.0333, 331, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'no', 'EFUS', '', '', '', '', 'Uppsala'),
(88, 'EFUT', 'small_airport', 'Udeljärvi Strip', 62.3000, 27.3000, 436, 'EU', 'FI', 'FI-72', 'Kuopio', 'no', 'EFUT', '', '', '', '', 'Udeljärvi'),
(89, 'EFUU', 'small_airport', 'Uittelijärvi Strip', 62.8667, 27.5667, 505, 'EU', 'FI', 'FI-72', 'Kuopio', 'no', 'EFUU', '', '', '', '', 'Uittelijärvi'),
(90, 'EFUV', 'small_airport', 'Ulvila Strip', 61.9333, 21.6333, 39, 'EU', 'FI', 'FI-29', 'Ulvila', 'no', 'EFUV', '', '', '', '', 'Ulvila'),
(91, 'EFUW', 'small_airport', 'Untamo Strip', 62.1667, 27.0000, 436, 'EU', 'FI', 'FI-72', 'Kuopio', 'no', 'EFUW', '', '', '', '', 'Untamo'),
(92, 'EFUX', 'small_airport', 'Uimoharju Strip', 62.2500, 28.7500, 436, 'EU', 'FI', 'FI-76', 'Savonlinna', 'no', 'EFUX', '', '', '', '', 'Uimoharju'),
(93, 'EFUY', 'small_airport', 'Upsunniemi Strip', 62.0667, 29.5667, 505, 'EU', 'FI', 'FI-76', 'Savonlinna', 'no', 'EFUY', '', '', '', '', 'Upsunniemi'),
(94, 'EFUZ', 'small_airport', 'Uurosselkä Strip', 62.1333, 26.6667, 436, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'no', 'EFUZ', '', '', '', '', 'Uurosselkä'),
(95, 'EFVA', 'small_airport', 'Vaaraslahti Strip', 62.1000, 27.5333, 436, 'EU', 'FI', 'FI-76', 'Savonlinna', 'no', 'EFVA', '', '', '', '', 'Vaaraslahti'),
(96, 'EFVB', 'small_airport', 'Valassela Strip', 62.1667, 29.1667, 505, 'EU', 'FI', 'FI-76', 'Savonlinna', 'no', 'EFVB', '', '', '', '', 'Valassela'),
(97, 'EFVC', 'small_airport', 'Varpaisjärvi Strip', 62.8500, 26.5000, 436, 'EU', 'FI', 'FI-72', 'Kuopio', 'no', 'EFVC', '', '', '', '', 'Varpaisjärvi'),
(98, 'EFVD', 'small_airport', 'Vaskijärvi Strip', 63.0333, 27.0833, 505, 'EU', 'FI', 'FI-72', 'Kuopio', 'no', 'EFVD', '', '', '', '', 'Vaskijärvi'),
(99, 'EFVE', 'small_airport', 'Vekaranjärvi Strip', 62.2667, 28.3333, 436, 'EU', 'FI', 'FI-76', 'Savonlinna', 'no', 'EFVE', '', '', '', '', 'Vekaranjärvi'),
(100, 'EFVF', 'small_airport', 'Vilajärvi Strip', 62.2000, 27.1667, 436, 'EU', 'FI', 'FI-75', 'Lappeenranta', 'no', 'EFVF', '', '', '', '', 'Vilajärvi');